# Generated by Django 4.1.2 on 2023-05-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_app', '0003_alter_building_building_id'),
        ('notification_app', '0002_notification_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='hits',
            field=models.ManyToManyField(blank=True, null=True, to='building_app.unit', verbose_name='بازدید'),
        ),
    ]
