# Generated by Django 4.1.2 on 2023-05-26 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0003_alter_notification_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ایجاد'),
        ),
    ]
