# Generated by Django 4.1.2 on 2024-04-08 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
    ]
