# Generated by Django 4.1.2 on 2023-06-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicechargestatus',
            name='payment_type',
        ),
    ]
