# Generated by Django 4.1.2 on 2023-06-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge_app', '0003_category_alter_servicecharge_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='category', verbose_name='تصویر'),
            preserve_default=False,
        ),
    ]
