# Generated by Django 4.1.2 on 2023-06-07 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charge_app', '0004_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecharge',
            name='category',
        ),
        migrations.AddField(
            model_name='servicecharge',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='charge_app.category', verbose_name='دسته بندی'),
            preserve_default=False,
        ),
    ]
