# Generated by Django 4.1.2 on 2024-04-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge_app', '0006_alter_servicechargestatus_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='servicechargestatus',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='servicechargestatus',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده/نشده'),
        ),
    ]
