# Generated by Django 4.1.2 on 2024-04-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge_app', '0007_alter_servicechargestatus_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicechargestatus',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipt', verbose_name='رسید کارت به کارت'),
        ),
    ]
