# Generated by Django 4.1.2 on 2024-04-09 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charge_app', '0008_servicechargestatus_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicechargestatus',
            name='is_paid',
        ),
    ]
