# Generated by Django 4.1.2 on 2024-04-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge_app', '0009_remove_servicechargestatus_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicechargestatus',
            name='status',
            field=models.CharField(choices=[('online_paid', 'پرداخت شده - آنلاین'), ('offline_paid', 'پرداخت شده - آفلاین'), ('unpaid', 'پرداخت نشده'), ('unpaid_waiting', 'پرداخت نشده - در انتظار بررسی'), ('unpaid_reject', 'پرداخت نشده - رد شده')], default='unpaid', max_length=50, verbose_name='وضعیت پرداخت'),
        ),
    ]
