# Generated by Django 4.1.2 on 2024-04-29 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('charge_app', '0010_alter_servicechargestatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecharge',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
    ]
