# Generated by Django 4.1.2 on 2023-05-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VipService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('slug', models.SlugField(max_length=10, verbose_name='نامک')),
                ('price', models.IntegerField(verbose_name='مبلغ')),
                ('time', models.IntegerField(verbose_name='مدت زمان به ماه')),
                ('max_unit', models.IntegerField(verbose_name='حداکثر واحد')),
            ],
            options={
                'verbose_name': 'سرویس ویژه',
                'verbose_name_plural': 'سرویس های ویژه',
            },
        ),
    ]
