# Generated by Django 4.1.2 on 2023-06-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip_service_app', '0002_alter_vipservice_max_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipservice',
            name='slug',
            field=models.SlugField(max_length=60, verbose_name='نامک'),
        ),
    ]
