# Generated by Django 4.1.2 on 2023-06-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip_service_app', '0003_alter_vipservice_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipservice',
            name='name',
            field=models.CharField(choices=[('پلن طلایی', 'پلن طلایی'), ('پلن نقره ای', 'پلن نقره ای'), ('پلن برنزی', 'پلن برنزی')], max_length=50, verbose_name='نام'),
        ),
    ]
