# Generated by Django 4.1.2 on 2022-11-24 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.CharField(default='VhbLq', max_length=5, unique=True, verbose_name='شناسه ساختمان')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
                ('image', models.ImageField(upload_to='building', verbose_name='تصویر')),
                ('rules', models.TextField(blank=True, null=True, verbose_name='قوانین')),
                ('credit', models.IntegerField(default=0, verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'ساختمان',
                'verbose_name_plural': 'ساختمان ها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='ServiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('amount', models.IntegerField(default=0, verbose_name='مبلغ')),
                ('divide_amount', models.CharField(choices=[('member', 'تقسیم بر تعداد ساکنین'), ('unit', 'تقسیم بر تعداد واحد ها')], max_length=30, verbose_name='تقسیم مبلغ')),
                ('expire_time', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building_app.building', verbose_name='برای ساختمان')),
                ('category', models.ManyToManyField(to='building_app.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'شارژ خدمات',
                'verbose_name_plural': 'شارژهای خدمات',
            },
        ),
        migrations.CreateModel(
            name='VipService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('price', models.IntegerField(verbose_name='مبلغ')),
                ('color', models.CharField(max_length=10, verbose_name='کد رنگ')),
                ('time', models.IntegerField(verbose_name='مدت زمان به ماه')),
                ('max_unit', models.IntegerField(verbose_name='حداکثر واحد')),
            ],
            options={
                'verbose_name': 'اشتراک ویژه',
                'verbose_name_plural': 'اشتراک های ویژه',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انقضا اشتراک')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('is_manager', models.BooleanField(default=False, verbose_name='مدیر ساختمان')),
                ('number_of_member', models.IntegerField(default=1, verbose_name='تعداد ساکنین')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building_app.building', verbose_name='برای ساختمان')),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ساکن')),
                ('vip_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='building_app.vipservice', verbose_name='اشتراک ویژه')),
            ],
            options={
                'verbose_name': 'واحد',
                'verbose_name_plural': 'واحد ها',
            },
        ),
        migrations.CreateModel(
            name='ServiceChargeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='مبلغ قابل پرداخت واحد')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده/نشده')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('payment_type', models.CharField(blank=True, choices=[('online', 'آنلاین'), ('cash', 'نقدی')], max_length=10, null=True, verbose_name='نوع پرداخت')),
                ('service_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building_app.servicecharge', verbose_name='شارژ خدمات')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building_app.unit', verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'وضعیت شارژ خدمات',
                'verbose_name_plural': 'وضعیت شارژهای خدمات',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building_app.building', verbose_name='برای ساختمان')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلانات',
            },
        ),
    ]
