# Generated by Django 4.1.2 on 2022-11-24 17:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('building_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='vip_plan',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='vip_time',
        ),
        migrations.AddField(
            model_name='building',
            name='vip_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building', to='building_app.vipservice', verbose_name='اشتراک ویژه'),
        ),
        migrations.AddField(
            model_name='building',
            name='vip_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انقضا اشتراک'),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_id',
            field=models.CharField(default='7j663', max_length=5, unique=True, verbose_name='شناسه ساختمان'),
        ),
    ]
