# Generated by Django 4.1.2 on 2023-05-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_id',
            field=models.CharField(default='O1SG1', max_length=5, unique=True, verbose_name='شناسه ساختمان'),
        ),
    ]
