# Generated by Django 4.1.2 on 2022-11-24 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building_app', '0002_remove_unit_vip_plan_remove_unit_vip_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_id',
            field=models.CharField(default='wq5jI', max_length=5, unique=True, verbose_name='شناسه ساختمان'),
        ),
        migrations.CreateModel(
            name='RequestPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheba_number', models.IntegerField(verbose_name='شماره شبا')),
                ('amount', models.IntegerField(verbose_name='مبلغ')),
                ('paid', models.BooleanField(default=False, verbose_name='پرداخت شده/نشده')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('request_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان درخواست')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building_app.building', verbose_name='ساختمان')),
            ],
        ),
    ]
