# Generated by Django 4.1.2 on 2023-06-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge_app', '0003_category_alter_servicecharge_category'),
        ('building_app', '0005_alter_building_building_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='building',
            name='building_id',
            field=models.CharField(default='ldV7Z', max_length=5, unique=True, verbose_name='شناسه ساختمان'),
        ),
    ]
