# Generated by Django 4.1.2 on 2022-11-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_app', '0006_remove_vipservice_color_alter_building_building_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipservice',
            name='slug',
            field=models.SlugField(default=1, max_length=10, verbose_name='نامک'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='building_id',
            field=models.CharField(default='3Kva6', max_length=5, unique=True, verbose_name='شناسه ساختمان'),
        ),
    ]
