# Generated by Django 4.1.2 on 2023-06-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_app', '0006_delete_category_alter_building_building_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_id',
            field=models.CharField(default='wGlq4', max_length=5, unique=True, verbose_name='شناسه ساختمان'),
        ),
    ]
