# Generated by Django 4.1.2 on 2023-05-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_app', '0007_vipservice_slug_alter_building_building_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vipservice',
            options={'verbose_name': 'سرویس ویژه', 'verbose_name_plural': 'سرویس های ویژه'},
        ),
        migrations.AlterField(
            model_name='building',
            name='building_id',
            field=models.CharField(default='qhliG', max_length=5, unique=True, verbose_name='شناسه ساختمان'),
        ),
    ]
