# Generated by Django 4.1.2 on 2023-06-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_app', '0009_alter_building_building_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='is_manager',
        ),
        migrations.AlterField(
            model_name='building',
            name='building_id',
            field=models.CharField(default='u1bkZ', max_length=5, unique=True, verbose_name='شناسه ساختمان'),
        ),
    ]
