# Generated by Django 4.1.2 on 2023-05-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_app', '0011_alter_building_building_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_id',
            field=models.CharField(default='2oh9u', max_length=5, unique=True, verbose_name='شناسه ساختمان'),
        ),
    ]
