# Generated by Django 4.1.2 on 2023-06-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_app', '0012_building_max_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='building', verbose_name='تصویر'),
        ),
    ]
