# Generated by Django 4.1.2 on 2024-04-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_app', '0014_building_card_number_building_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='card_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره کارت'),
        ),
    ]
