# Generated by Django 4.1.2 on 2024-04-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_app', '0015_alter_building_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='owner_card',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='صاحب کارت'),
        ),
    ]
