# Generated by Django 4.1.2 on 2023-06-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_alter_otp_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=1, verbose_name='مدیر ساختمان'),
            preserve_default=False,
        ),
    ]
