# Generated by Django 4.1.2 on 2023-06-29 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building_app', '0013_alter_building_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='سوال')),
                ('created', models.DateTimeField(verbose_name='زمان ایجاد')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building_app.building', verbose_name='ساختمان')),
            ],
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=50, verbose_name='گزینه')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll_app.poll', verbose_name='سوال')),
                ('unit', models.ManyToManyField(related_name='vote', to='building_app.unit')),
            ],
        ),
    ]
