# Generated by Django 4.1.2 on 2023-06-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': ' سوال نظرسنجی', 'verbose_name_plural': ' سوالات نظرسنجی ها'},
        ),
        migrations.AlterModelOptions(
            name='polloption',
            options={'verbose_name': 'گزینه نظرسنجی', 'verbose_name_plural': 'گزینه های نظرسنجی'},
        ),
        migrations.AlterField(
            model_name='poll',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
    ]
