# Generated by Django 4.1.2 on 2023-06-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_app', '0013_alter_building_image'),
        ('poll_app', '0002_alter_poll_options_alter_polloption_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polloption',
            name='unit',
        ),
        migrations.AddField(
            model_name='polloption',
            name='units',
            field=models.ManyToManyField(related_name='votes', to='building_app.unit', verbose_name='رای دهندگان'),
        ),
    ]
